packages:
  - "packages/*"

catalogs:
  devDeps:
    "@biomejs/biome": "^2.3.8"
    "@ducktors/tsconfig": "^1.0.0"
    "@types/node": "^22.0.2"
    "@types/mime-types": "^2.1.1"
    c8: "^8.0.1"
    rimraf: "^5.0.10"
    tsx: "^3.13.0"
    typescript: "^5.2.2"

  prodDeps:
    "mime-types": "^2.1.35"
    "tslib": "^2.5.0"
